name: Replace metadata placeholders
description: Replaces various PSMC-namespaced pieces of data in the pack.mcmeta with their respective values

runs:
  using: composite
  steps:
    - name: Get current date
      id: date
      shell: bash
      run: |
        echo "::set-output name=date::$(date + '%m/%d/%Y')"
    - name: Replace version ID placeholder
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "PSMCVersion"
        replace: "${{ github.ref_name }}"
        include: "pack/pack.mcmeta"
        regex: false
    - name: Replace version date placeholder
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "PSMCDate"
        replace: "${{ steps.date.outputs.date }}"